### ISSUE TITLE
fix or remove StreamingBody.last_modified()

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#330] opened 2021-10-15 00:39 UTC
In model.py in function `StreamingBody.last_modified()` on line 167 we return `datetime.strptime(...)`, however this should be `datetime.datetime.strptime(...)`. Further, `StreamingBody.last_modified()` doesn't appear to be used anywhere in the codebase. Consider removing it.

Ref: https://github.com/planetlabs/planet-client-python/pull/318#pullrequestreview-772756697

**Comment by kevinlacaille** [comment] 2021-10-19 15:24
This is a duplicate of the issue I created a couple of weeks ago: https://github.com/planetlabs/planet-client-python/issues/326

**Closed by kevinlacaille** 2021-10-19 15:24 UTC
Labels: fixup
