### ISSUE TITLE
Planet SDK v2 - Subscriptions: Unable to update the subscription with ID & update file

### ISSUE THREAD

**Issue by rajashekarmamidala** [planetlabs/planet-client-python#659] opened 2022-08-02 09:56 UTC
**Environment**: planet, version 2.0a1

**Test Steps**:
1. Create a subscription as below

`C:\planet_cli2\planet-client-python>planet subscriptions create sub_create.json`

`{"name": "QE Simple-new format-Skysatscene-PCLi", "source": {"type": "catalog", "parameters": {"asset_types": ["ortho_analytic"], "item_types": ["SkySatScene"], "geometry": {"coordinates": [[[-122.78320312499999, 37.56199695314352], [-121.95373535156249, 37.56199695314352], [-121.95373535156249, 38.16911413556086], [-122.78320312499999, 38.16911413556086], [-122.78320312499999, 37.56199695314352]]], "type": "Polygon"}, "start_time": "2022-07-20T15:57:05Z", "end_time": "2022-07-31T23:55:55Z"}}, "delivery": {"type": "google_cloud_storage", "parameters": {"bucket": "subscriptions_qe", "credentials": "<REDACTED>"}}, "created": "2022-07-20T15:51:17.274266Z", "_links": {"_self": "https://api.planet.com/subscriptions/v1/91125d62-f0cd-44da-9143-06c50ed2aadb"}, "status": "preparing", "id": "91125d62-f0cd-44da-9143-06c50ed2aadb", "updated": "2022-07-20T15:51:17.274266Z"}`
2. Now update the subscription by modifying the file ( End_date) with below command

**planet subscriptions update 91125d62-f0cd-44da-9143-06c50ed2aadb sub_create_update.json**
**Expected**: It should update the subscription properly

**Actual**: it is displaying error as below

`Error: {"error":{"reason":"Request failed schema validation","details":["parameter 'subscriptionId' in path has an error: JSON string doesn't match the format 'uuid (regular expression `^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`)' | "]}}`
[sub_create _update.json.txt](https://github.com/planetlabs/planet-client-python/files/9241497/sub_create._update.json.txt)
[sub_create.json.txt](https://github.com/planetlabs/planet-client-python/files/9241500/sub_create.json.txt)

**Comment by sgillies** [comment] 2022-09-07 02:34
Also a duplicate of #687. The fix will be in 2.0a3.

**Closed by sgillies** 2022-09-07 02:34 UTC
