### ISSUE TITLE
Implement --search-id in Orders CLI

### ISSUE THREAD

**Issue by kevinlacaille** [planetlabs/planet-client-python#520] opened 2022-05-09 14:41 UTC
Implement the --search-id options in the Orders CLI. From the [CLI Interface spec](https://docs.google.com/document/d/1DSMWbJ0spBBzPFc_KcdFQo9kuCAgTuk2x1kw6_D0UVI/edit#heading=h.ick5vgthlwe1):

**Example code in Order CLI**
- `planet.cli.orders.request()` click option:
```
@click.option(
    '--search-id',
    help='NOT YET IMPLIMENTED. ID of search from which to populate item IDs.',
    type=click.STRING,
    callback=split_list_arg,
    required=False)
```
- `planet.cli.orders.request()` function logic:
```
if id and search_id:
    raise click.BadParameter("Specify only one of '--id' or '--search-id'")
```

**Functionality to achieve within `planet orders request`**
- [ ] Accomplishing the same thing but with a search id instead of item ids:
```
$ planet orders request \
    --name test_order \
    --bundle analytic \
    --search-id 897802165e8d4bd587e342a4b399eda6 \
    --clip - < aoi.geojson
```
- [ ] To the item ids can also be read from a saved search:
```
$ planet orders get 49b8d32e-2fba-4924-bd38-f7344aa48d91 > \
planet orders request --search-id 897802165e8d4bd587e342a4b399eda6
```

**Comment by jreiberkyle** [comment] 2022-05-09 17:18
This looks like a duplicate of #388. The last example here, `planet orders request --search-id 897802165e8d4bd587e342a4b399eda6` looks like it may be missing a `--like -`.

**Comment by kevinlacaille** [comment] 2022-05-10 12:58
Oh right, I should have taken a look before ticketing! I'll close this and mark as a duplicate. In regards to the example, this comes directly from the spec. Should it instead be: 
`planet orders get 49b8d32e-2fba-4924-bd38-f7344aa48d91 > \
planet orders request --like - --search-id 897802165e8d4bd587e342a4b399eda6
`
?

**Comment by jreiberkyle** [comment] 2022-05-10 16:39
yep that looks right!

**Closed by jreiberkyle** 2022-05-10 16:39 UTC
Labels: duplicate, CLI/SDK Interface

**Comment by kevinlacaille** [comment] 2022-05-10 18:13
Perfect, I updated the CLI Interface doc!

**Comment by jreiberkyle** [comment] 2022-05-11 01:30
Where did you update the doc? I was thinking what I was telling you was coming from that doc so I'm surprised to hear a change was required.

**Comment by kevinlacaille** [comment] 2022-05-11 14:19
@jreiberkyle you can check the version history for more detail, but it's under 
`Orders API > request > Interface > 2. Starting from an order description` and [link here](https://docs.google.com/document/d/1DSMWbJ0spBBzPFc_KcdFQo9kuCAgTuk2x1kw6_D0UVI/edit?disco=AAAAY29JcV4).

**Comment by jreiberkyle** [comment] 2022-05-11 16:08
@kevinlacaille thank you! I tried checking the version history but didn't figure out how to highlight the changes. thanks for the comment in the doc, that helped :)
