### ISSUE TITLE
protect against invalid asset location url for download_asset

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#299] opened 2021-07-17 06:38 UTC
Currently, `OrdersClient.download_asset` explodes if an invalid location url is passed. Protect against this by gracefully throwing an exception.

Test:
```python
@respx.mock
@pytest.mark.asyncio
async def test_download_asset_invalid_location(tmpdir, session):
    dl_url = TEST_URL + 'download/?token=IAmAnInvalidToken'

    mock_resp = httpx.Response(404)  # yup, this is what the server responds with. nothin
    respx.get(dl_url).return_value = mock_resp

    cl = OrdersClient(session, base_url=TEST_URL)
    _ = await cl.download_asset(dl_url, directory=str(tmpdir))
```

**Comment by cholmes** [comment] 2022-05-03 17:43
This seems to be roughly a duplicate of #325, so we'll close this.

**Closed by cholmes** 2022-05-03 17:43 UTC
Labels: bug, error handling
