### ISSUE TITLE
Maintain the data api spec separate from the orders api spec

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#960] opened 2023-05-19 19:18 UTC
The SDK has been using the orders product bundle spec to validate the orders, subscriptions, and data api.

In #956 it was found that this was inadequate, as the data api supports an item-type that is not supported by the orders api: SkySatVideo. This was corrected in the short term by #959, which added `SkySatVideo` as a data api item type. This fixed the bug but introduced a maintenance issue - now a function in the `spec` method must be updated by hand every time the data api introduces an item type the orders api does not support - and this approach does not work if the orders api introduces an item type not supported by the data api.

To alleviate this maintenance issue and make it easier to keep the SDK up to date with the API product structures, maintain a spec specific to the data api and separate orders and data validation, suggestion, and correction.

**Comment by tbarsballe** [comment] 2024-09-05 19:09
Duplicate of #663

**Closed by tbarsballe** 2024-09-05 19:09 UTC
Labels: fixup, maintenance
